---
- name: Install Apache on Ubuntu
  hosts: slave1
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Start Apache service
      service:
        name: apache2
        state: started

- name: Set up Nginx web server
  hosts: slave2
  become: yes
  tasks:
    - name: Update apt cache and ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
